export const SET_PRODUCTS = "PRODUCTS/SET_PRODUCTS";
export const SET_CATEGORIES = "CATEGORIES/SET_CATEGORIES";
export const SET_NEWS = "NEWS/SET_NEWS";
export const SET_NEWS_ITEM = "NEWS/SET_NEWS_ITEM";
export const SHOW_LOADER = "APP/SHOW_LOADER";
export const HIDE_LOADER = "APP/HIDE_LOADER";